### ISSUE TITLE
Task List Agenda

### ISSUE THREAD

**Issue by liamawhite** [notedownorg/task#14]
- [x] Display overdue, due, completed tasks for given day
- [x] Grouped by status and then priority (order: doing->todo->blocked->done)
- [x] Completed tasks = greyed +strikethrough, doing = green , blocked = red, 
- [x] Task add automatically has due date of agenda date
- [x] Navigation to different days
- [x] Move completed to right hand side
- [x] Add priority to list
